name: Automate PR
on:
  issues:
    types:
      # - labeled     
      - opened
      - reopened
      # only needed labeled, using opened and reopened for time being 

# permissions:
#   contents: read

jobs:
  Automate:
    # if: github.event.label.name == 'Automate'
    runs-on: ubuntu-latest
    # permissions:
    #   issues: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Devils-Knight/Automate-PR
    
      - name: Automate PR
        uses: Devils-Knight/Automate-PR@master
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}